#! /bin/bash 
# COLOR-SCRIPTS by Derek Taylor (DistroTube)
# A simple script that creates an openbox pipemenu that runs Color-Scripts
# (https://github.com/dwt1/Color-Scripts) in a terminal window.
# 
# Color-Scripts was forked from Color-Scripts (https://github.com/stark/Color-Scripts)
#
# This program is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License version 3 as published by the Free Software Foundation.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without 
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see: http://www.gnu.org/licenses
#
# OpenBox "Color-Scripts" pipe-menu
# Outputs a menu roughly akin to:
#
#    Color Scripts
#    ----------
#    <color script 1>
#    <color script 2>
#    <color script 3>
#    ...
#
# Usage:
#
# 1. Copy this file somewhere on your path (I like: /.config/openbox/pipemenus ) and make it executable
# 2. Add the following line somewhere to your /.config/openbox/menu.xml
#
#    <menu id="color-scripts" label="Color Scripts" execute="color-scripts" />
#
# 3. Reconfigure openbox


# output the initial menu
# NOTE: If you do not use the "termite" terminal program or the "ranger" file manager, edit the <command> below.
cat <<EOF
<openbox_pipe_menu>
    <item label="Color Scripts">
        <action name="Execute">
            <command>
                 termite -e 'ranger ~/color-scripts' 
            </command>
        </action>
    </item>
EOF


# seperate the main command from the virtuals
echo "    <separator/>"

echo "    <menu id=\"color-scripts-01-15\" label=\"01-15\">"
# each color script listed in the menu
for file in $(ls ~/color-scripts/* | head -15); do
NAME=$(echo "$file" | rev | cut -d"/" -f1 | rev)
# NOTE: If you do not use the "termite" terminal program, then change "termite" to your preferred terminal (ex. xterm, urxvt, etc.)
echo "<item label=\"$NAME\"><action name=\"Execute\"><execute>termite -e '$file' -t '$file'</execute></action></item>"
done
echo "    </menu>"

echo "    <menu id=\"color-scripts-16-30\" label=\"16-30\">"
# each color script listed in the menu
for file in $(ls ~/color-scripts/* | tail -35 | head -15); do
NAME=$(echo "$file" | rev | cut -d"/" -f1 | rev)
# NOTE: If you do not use the "termite" terminal program, then change "termite" to your preferred terminal (ex. xterm, urxvt, etc.)
echo "<item label=\"$NAME\"><action name=\"Execute\"><execute>termite -e '$file' -t '$file'</execute></action></item>"
done
echo "    </menu>"

echo "    <menu id=\"color-scripts-31-45\" label=\"31-45\">"
# each color script listed in the menu
for file in $(ls ~/color-scripts/* | tail -20 | head -15); do
NAME=$(echo "$file" | rev | cut -d"/" -f1 | rev)
# NOTE: If you do not use the "termite" terminal program, then change "termite" to your preferred terminal (ex. xterm, urxvt, etc.)
echo "<item label=\"$NAME\"><action name=\"Execute\"><execute>termite -e '$file' -t '$file'</execute></action></item>"
done
echo "    </menu>"

echo "    <menu id=\"color-scripts-46+\" label=\"46+\">"
# each color script listed in the menu
for file in $(ls ~/color-scripts/* | tail -5 | head -15); do
NAME=$(echo "$file" | rev | cut -d"/" -f1 | rev)
# NOTE: If you do not use the "termite" terminal program, then change "termite" to your preferred terminal (ex. xterm, urxvt, etc.)
echo "<item label=\"$NAME\"><action name=\"Execute\"><execute>termite -e '$file' -t '$file'</execute></action></item>"
done
echo "    </menu>"

# and finally...
echo "</openbox_pipe_menu>"

