#!/bin/sh

HERE=$(dirname $(readlink -f $0))
SCREEN_SIZE=${SCREEN_SIZE:-1000x750}
XDISPLAY=:1

Xephyr +extension RANDR -screen ${SCREEN_SIZE} ${XDISPLAY} -ac &
(
  sleep 1
  env DISPLAY=${XDISPLAY} /usr/bin/qtile -l INFO $@ &
  env DISPLAY=${XDISPLAY} xterm &
  env DISPLAY=${XDISPLAY} xeyes
)
